# CEP Problem Configuration

# =============================================================================
# METADATA
# =============================================================================
metadata:
  instance_name: "benders_run_cep"

# =============================================================================
# INPUT FILES
# =============================================================================
input_files:
  smps_core_file: "./smps_data/cep/cep.mps"
  smps_time_file: "./smps_data/cep/cep.tim"
  smps_sto_file: "./smps_data/cep/cep.sto"
  input_h5_basis_file: "./cep_100scen_results.h5"

# =============================================================================
# ARGMAX POOL - GPU Memory and Dual Solution Storage
# =============================================================================
argmax_pool:
  MAX_PI: 500000
  MAX_OMEGA: 1000000
  SCENARIO_BATCH_SIZE: 1000
  NUM_CANDIDATES: 8
  primal_feas_tol: 1e-3 (not in original JSON)

# =============================================================================
# ALGORITHM PARAMETERS - Core Algorithm Settings
# =============================================================================
algorithm_parameters:
  ETA_LOWER_BOUND: -1e7
  NUM_SAMPLES_FOR_POOL: 1000000
  tolerance: 1e-3
  num_duals_to_add_per_iteration: 1000
  argmax_tol_cutoff: 1e-3
  num_workers: 4
  num_lp_scenarios_per_iteration: 10000
  lp_scenario_selection_strategy: "systematic"
  max_iterations: 10

# =============================================================================
# REGULARIZATION CONTROL - Trust Region Parameters
# =============================================================================
regularization_control:
  initial_rho: 1.0
  gamma: 0.5
  rho_decrease_factor: 0.5
  rho_increase_factor: 2.0
  min_rho: 1e-2
  max_rho: 1e5

# =============================================================================
# VALIDATION - Solution Quality Assessment
# =============================================================================
validation:
  enable_validation: true        
  validation_N1: 50000          
  validation_N2: 1000000        
  validation_confidence_level: 0.95
  validation_seed: 12345        

# =============================================================================
# LOGGING - Output and Debugging
# =============================================================================
logging:
  log_dir: "logs"