# STORM Problem Configuration  

# =============================================================================
# METADATA
# =============================================================================
metadata:
  instance_name: "benders_run_storm"

# =============================================================================
# INPUT FILES
# =============================================================================
input_files:
  smps_core_file: "./smps_data/storm/storm.mps"
  smps_time_file: "./smps_data/storm/storm.tim"
  smps_sto_file: "./smps_data/storm/storm.sto"
  input_h5_basis_file: "./storm_100scen_results.h5"

# =============================================================================
# ARGMAX POOL - GPU Memory and Dual Solution Storage
# =============================================================================
argmax_pool:
  MAX_PI: 200000
  MAX_OMEGA: 1000000
  SCENARIO_BATCH_SIZE: 10000
  NUM_CANDIDATES: 8
  primal_feas_tol: 1e4

# =============================================================================
# ALGORITHM PARAMETERS - Core Algorithm Settings
# =============================================================================
algorithm_parameters:
  ETA_LOWER_BOUND: -1e9
  NUM_SAMPLES_FOR_POOL: 1000000
  tolerance: 1e3
  num_duals_to_add_per_iteration: 5000
  argmax_tol_cutoff: 1e3
  num_workers: 192
  num_lp_scenarios_per_iteration: 10000
  lp_scenario_selection_strategy: "systematic"
  max_iterations: 300

# =============================================================================
# REGULARIZATION CONTROL - Trust Region Parameters
# =============================================================================
regularization_control:
  initial_rho: 100
  gamma: 0.5
  rho_decrease_factor: 0.5
  rho_increase_factor: 2.0
  min_rho: 1e-2
  max_rho: 1e6

# =============================================================================
# VALIDATION - Solution Quality Assessment
# =============================================================================
validation:
  enable_validation: true        
  validation_N1: 200000          
  validation_N2: 10000000        
  validation_confidence_level: 0.95
  validation_seed: 123456        

# =============================================================================
# LOGGING - Output and Debugging
# =============================================================================
logging:
  log_dir: "logs"